### ISSUE TITLE
Missing #include <cpprest/filestream.h>

### ISSUE THREAD

**Issue by mitch-besser** [Pintulalm/Restweb#3]
handler.cpp is missing a required header. 

#include <cpprest/filestream.h>

It would be nice if the headers that are used are there for the .cpp files and not bundled into headers. This makes reuse a lot easier and improves readability. It would also be nice if there was a solution file so people who use Microsoft can compile the project.

**Comment by Meenapintu** [comment]
>#include <cpprest/filestream.h>

is included in  include/stdafx.h   header file with is header file for cpprest headers.
so it already included in heandler.cpp as handler.h is header file for handler.cpp and stdafx.h included in handler.h file 
So please try to cmake then make again because when I'm building , it builds successfully.
[tested on[Ubuntu bash on windows and Kali Linux]

If it doesn't work ,take a new clone , because may be case that cmake generated files causing problem   ( files that haven't updated with cmake . command )  and now I have removed them from tracker .  

Let me know if  you still have trouble in build 

And Yes about Header . 
As much as I know , mostly header files are included in header file of source file.
like handler.h is a header file of handler.cpp
another advantage is that when you are linking it to another program then you just have to include header file, rest will be done by linker so it make independence plus clarity of project according to me.   

and yes I will try to make a visual studio solution file  but it will take some time to update as I don't prefer visual studio while coding in c++ and it's not Microsoft specific. 

> you can still compile it on windows as it uses Cmake to build .
 Or use Ubuntu bash on windows of you are windows user.

**Comment by mitch-besser** [comment]
I Re-cloned as you suggested. Following the instructions still does not work. If this is not a cross platform project, please indicate so on the README.md which platforms/tools have been confirmed to work. 

Below is the error if that helps. VS2015 on Windows 7. 

---
C:\Users\mbesser\dev\tmp\Restweb>cmake .
-- Building for: Visual Studio 14 2015
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio
14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio
14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studi
o 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studi
o 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/mbesser/dev/tmp/Restweb

C:\Users\mbesser\dev\tmp\Restweb>make
process_begin: CreateProcess(NULL, sh.exe -c "/usr/bin/cmake -H/media/pintulalm/
New Volume/workspace/Restweb -B/media/pintulalm/New Volume/workspace/Restweb --c
heck-build-system CMakeFiles/Makefile.cmake 0", ...) failed.
make (e=2): The system cannot find the file specified.
makefile:206: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 2

C:\Users\mbesser\dev\tmp\Restweb>

**Comment by Meenapintu** [comment]
Hi , 
why is this >....  -H/media/pintulalm/New Volume/workspace/Restweb -B/media/pintulalm/New Volume/workspace/Restweb ...

This is my pc configuration , cmake is not overwriting make file newly generated . [ I'm sorry that I by mistake forgot to remove "makefile" from git tracker ]  , that's why this error is there,it using my pc  generated make-file not cmake generated .
 
and yes I haven't tested on windows but it should work .

**Comment by Meenapintu** [comment]
HI , 
I just made a Visual studio (2015) solution and tested it  right now and just uploading it in a while . 

I have updated visual studio solution in a new branch ["vs15_v140"] and also tested it on visual studio 2015 community edition . 
if you still get error then ,please let me know
