### ISSUE TITLE
unicode under win platform

### ISSUE THREAD

**Issue by amigo421** [Pintulalm/Restweb#4]
> C:\dev\workspace\Restweb\src\handler.cpp(91): error C2440: 'initializing': cannot convert from 'const wchar_t [32]' to 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'

from my perspective , it happens because you are using unicode strings under windows however I don't see any flags in cmakelists to specify this. 

I suppose you build this in visual studio which sets _UNICODE by default? have you tried to build the project using cmake only? without IDE?

**Comment by Meenapintu** [comment]
Yes I tried and I also got same error but I didn't  debug it due to some personal reason  so  I build it with ide "and that's why I created new branch vs15_v140 for win ". I will try to debug it and fix the error but not right now.
>hint:  may be because I have used U("string" ) in handler.cpp file . so by just simply using standard c++ string can solve the problem.( I will try that fix whenever I'm switching to windows )

if you have time and willing to help others also , you are more than welcome to contribute .
